# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dployr < Formula
  desc "Your app, your server, your rules!"
  homepage "https://github.com/dployr-io/homebrew-dployr"
  version "0.4.1-beta.14"
  license "MIT"

  depends_on "caddy"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.1-beta.14/dployr-Darwin-x86_64.tar.gz"
      sha256 "23e9ca24a31217ac9d8153d33a3fc804761da851a729a683d8daff521892812a"

      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.1-beta.14/dployr-Darwin-arm64.tar.gz"
      sha256 "bf7198db57b2c59a7ec863be0500ebd05f96e7fdeb7dd9d03993a894588bf0ed"

      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.1-beta.14/dployr-Linux-x86_64.tar.gz"
      sha256 "b7ed0680a9a2c5b86c090ee0fe08d5478fcad1deba960bff6d1ece030eefb2ee"
      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.1-beta.14/dployr-Linux-arm64.tar.gz"
      sha256 "1d23bb454841fc818d24fb50160787e8e0a4bd65b681d35010bf05ba74489a47"
      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
  end

  test do
    system "#{bin}/dployr", "--version"
  end
end
