# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dployr < Formula
  desc "Your app, your server, your rules!"
  homepage "https://github.com/dployr-io/homebrew-dployr"
  version "0.4.8"
  license "Apache License, Version 2.0"

  depends_on "caddy"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.8/dployr-Darwin-x86_64.tar.gz"
      sha256 "619888adbda35e8dc10bf73ab73c884dc08236465521f4cc2813ecda06adc419"

      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.8/dployr-Darwin-arm64.tar.gz"
      sha256 "2d5f771b8b50d216a9dfc35337f3c36379edf63bfaf32413902b04b97bd6e785"

      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.8/dployr-Linux-x86_64.tar.gz"
      sha256 "0ac8b969058c5fcfd6ac846b0ef96a76a51aaa1e2ad14af141d43a5a4ba0611b"
      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.8/dployr-Linux-arm64.tar.gz"
      sha256 "cb9d207f6d0fb4b78b9f4c6b6fcc49825a746111f17becb1fedd74468789c37f"
      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
  end

  test do
    system "#{bin}/dployr", "--version"
  end
end
