# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dployr < Formula
  desc "Your app, your server, your rules!"
  homepage "https://github.com/dployr-io/homebrew-dployr"
  version "0.4.7-beta.3"
  license "Apache License, Version 2.0"

  depends_on "caddy"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.7-beta.3/dployr-Darwin-x86_64.tar.gz"
      sha256 "bb22c3c03e0eb23378ac5612d392102d8501656cd1fa20f7992153bc6a2348bd"

      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.7-beta.3/dployr-Darwin-arm64.tar.gz"
      sha256 "00c49900b2b64674a52b6bc0bf483d04497d90ab390bfc21d4677791c9206f30"

      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.7-beta.3/dployr-Linux-x86_64.tar.gz"
      sha256 "d5f74faf0a802aaf82ef2e10be40ec35d6b9abecabd76118dbd90c7a41177428"
      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dployr-io/dployr/releases/download/v0.4.7-beta.3/dployr-Linux-arm64.tar.gz"
      sha256 "988307f4f7b470025e67796443352ffbd8feddb93cd8a6c574a777ae3ece71a0"
      def install
        bin.install "dployr"
        bin.install "dployrd"
      end
    end
  end

  test do
    system "#{bin}/dployr", "--version"
  end
end
